
var EVENT_SIDEBAR_RESIZE = 'EVENT_SIDEBAR_RESIZE';
var EVENT_LINE_RESIZE = 'EVENT_LINE_RESIZE';

var SLIDER_LEFT = 'SLIDER_LEFT';
var SLIDER_RIGHT = 'SLIDER_RIGHT';

var EVENT_SLIDER_POSITION = 'EVENT_SLIDER_POSITION';
var EVENT_SLIDER_POSITION_LEFT = 'EVENT_SLIDER_POSITION.LEFT';
var EVENT_SLIDER_POSITION_RIGHT = 'EVENT_SLIDER_POSITION.RIGHT';
